[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    '''user-guides'''
  ]
        
  # Ignore based on any subset of the line
  regexes = [
  ]
