site_name: Kuadrant Documentation
site_url: https://docs.kuadrant.io/
theme:
  name: material
  logo: assets/logo.png
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - multirepo:
      cleanup: true
      keep_docs_dir: true
      repos:
        - section: Kuadrant Operator
          import_url: 'https://github.com/kuadrant/kuadrant-operator?edit_uri=/blob/main/&branch=main&docs_dir=doc/*&extra_imports=["README.md"]'
        - section: Authorino
          import_url: 'https://github.com/kuadrant/authorino?edit_uri=/blob/main/&branch=main&extra_imports=["README.md"]'
        - section: Authorino Operator
          import_url: 'https://github.com/kuadrant/authorino-operator?edit_uri=/blob/main/&branch=main&extra_imports=["README.md"]'
        - section: Limitador
          import_url: 'https://github.com/kuadrant/limitador?edit_uri=/blob/main/&branch=main&docs_dir=doc/*&extra_imports=["README.md"]'
        - section: Multicluster Gateway Controller
          import_url: 'https://github.com/kuadrant/multicluster-gateway-controller?edit_uri=/blob/main/&branch=main&extra_imports=["README.md"]'
        - section: Architecture
          import_url: 'https://github.com/kuadrant/architecture?edit_uri=/blob/main/&branch=main&extra_imports=["README.md"]'
