site_name: Kuadrant Documentation
site_url: https://docs.kuadrant.io/
theme:
  name: material
plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
      # if set the docs directory will not be removed when importing docs.
      # When using this with a nav section in an imported repo you must keep the
      # docs directory in the path (e.g., docs/path/to/file.md).
      keep_docs_dir: true
      repos:
        - section: Kuadrant Operator
          import_url: 'https://github.com/kuadrant/kuadrant-operator?edit_uri=/blob/main/&branch=main&docs_dir=doc/*'
        - section: Authorino
          import_url: 'https://github.com/kuadrant/authorino?edit_uri=/blob/main/&branch=main'
        - section: Limitador
          import_url: 'https://github.com/kuadrant/limitador?edit_uri=/blob/main/&branch=main&docs_dir=doc/*'
        - section: Multicluster Gateway Controller
          import_url: 'https://github.com/kuadrant/multicluster-gateway-controller?edit_uri=/blob/main/&branch=main'
        - section: Architecture
          import_url: 'https://github.com/kuadrant/architecture?edit_uri=/blob/main/&branch=main'
        - section: Authorino Operator
          import_url: 'https://github.com/kuadrant/authorino-operator?edit_uri=/blob/main/&branch=main'
